CREATE TABLE cryptocurrency
(
    id     BIGINT       NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    CONSTRAINT pk_cryptocurrency PRIMARY KEY (id)
);

INSERT INTO cryptocurrency
VALUES (90, 'BTC'),
       (80, 'ETH'),
       (48543, 'SOL');



CREATE TABLE currency_price
(
    symbol VARCHAR(255) NOT NULL,
    price  DOUBLE PRECISION,
    CONSTRAINT pk_currencyprice PRIMARY KEY (symbol)
);

CREATE TABLE price_notify
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    symbol   VARCHAR(255),
    price    DOUBLE PRECISION,
    CONSTRAINT pk_pricenotify PRIMARY KEY (id)
);