spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/task
  username: test_user
  password: test_user

 messages:
  basename: localization/messages
  fallback-to-system-locale: false

 mvc:
  pathmatch:
   matching-strategy: ant_path_matcher

 flyway:
  locations:
   - classpath:db
  out-of-order: true